language: cpp
dist: trusty
sudo: false
os: linux

compiler:
  - gcc
  - clang

env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
  -
matrix:
  include:
    - env: COMPILER=g++-7 BUILD=Debug STANDARD=11
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost1.69-all-dev'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.69
    - env: COMPILER=g++-7 BUILD=Release STANDARD=11
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost1.69-all-dev'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.69

install:
  # скрипт настройки среды и установки зависимостей:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  # скрипт сборки и тестирования проекта:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ctest --output-on-failure
